
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'impro.dynv6.net -> http://mehc:3000'
      STAGE: 'production' # Don't use production until staging works
      # STAGE: local
    volumes:
      - https-portal-data:/var/lib/https-portal

  mehc:
    image: rodgeradr/mehc
    ports:
      - '3000:3000'

volumes:
    https-portal-data: # Recommended, to avoid re-signing when upgrading HTTPS-PORTAL


