name: Build

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        # registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - run: ./init-db.sh
    - run: docker build -t rodgeradr/mehc .
    - run: docker push rodgeradr/mehc
    # - name: Build web app
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: 20.x
